[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "black", args = ["-", "-q"] }
auto-format = true

[[language]]
name = "htmldjango"
scope = "source.htmldjango"
file-types = []
roots = []
auto-format = true
formatter = { command = "djlint", args = ["-", "--reformat", "--quiet"] }

[[grammar]]
name = "htmldjango"
source = { git = "https://github.com/interdependence/tree-sitter-htmldjango", rev = "b2dba02eddab66be669022320273d0dfe1ff923d" }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }

[[language]]
name = "gotmpl"
auto-format = true
language-servers = ["gopls", "emmet-ls", "tailwindcss-ls"]
formatter = { command = "djlint", args = ["-", "--reformat", "--quiet", "--profile=golang"] }

[[language]]
name = "templ"
auto-format = true
language-servers = ["templ", "emmet-ls", "tailwindcss-ls"]

[language-server.tailwindcss-ls]
config = { userLanguages = { templ = "html", "gotmpl" = "html" } }

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]
